### ISSUE TITLE
Error when tried to use the elevator

### ISSUE THREAD

**Issue by xsoskiller** [GouveiaXS/elevators#13]
i got this error when i tried to use it after i setup my config

Screenshot of the error
![image](https://user-images.githubusercontent.com/66858021/236651302-992eb577-7a59-4b11-9697-025fd7b5bd0c.png)
Screenshot of the actual config
![image](https://user-images.githubusercontent.com/66858021/236651279-1b29b707-7d81-49ba-8b3f-5380ae323a0a.png)
![image](https://user-images.githubusercontent.com/66858021/236651273-7d8e7697-a22f-40c4-8869-c1b632c2aaa5.png)

**Comment by GouveiaXS** [comment]
Do you have another close bracket to close the last table?
On May 6, 2023 6:09 PM, Dlink4 wrote:


i got this error when i tried to use it after i setup my config

Screenshot of the error
![image](https://user-images.githubusercontent.com/66858021/236651248-5348d17f-6638-46e4-8bdc-f88d5aa8bec4.png)

Screenshot of the actual config
![image](https://user-images.githubusercontent.com/66858021/236651279-1b29b707-7d81-49ba-8b3f-5380ae323a0a.png)
![image](https://user-images.githubusercontent.com/66858021/236651273-7d8e7697-a22f-40c4-8869-c1b632c2aaa5.png)


-- 
Reply to this email directly or view it on GitHub:
https://github.com/GouveiaXS/angelicxs-elevators/issues/13

**Comment by GouveiaXS** [comment]
Sorry, there error didn't load correctly the first time.The error is related to you ox_libs.To fix this you must follow the instructions by Config.UseOxLibs in the config and add the extra lines to the fxmanifest.
On May 6, 2023 6:09 PM, Dlink4 wrote:


i got this error when i tried to use it after i setup my config

Screenshot of the error
![image](https://user-images.githubusercontent.com/66858021/236651248-5348d17f-6638-46e4-8bdc-f88d5aa8bec4.png)

Screenshot of the actual config
![image](https://user-images.githubusercontent.com/66858021/236651279-1b29b707-7d81-49ba-8b3f-5380ae323a0a.png)
![image](https://user-images.githubusercontent.com/66858021/236651273-7d8e7697-a22f-40c4-8869-c1b632c2aaa5.png)


-- 
Reply to this email directly or view it on GitHub:
https://github.com/GouveiaXS/angelicxs-elevators/issues/13
