### ISSUE TITLE
bad code

### ISSUE THREAD

**Issue by 766974616c79** [GouveiaXS/elevators#15]
hi, I wanted to say that this part of the code needs to be rewritten

(line 127)
```lua
CreateThread(function()
	if Config.Use3DText then
		for elevatorName, elevatorFloors in pairs(Config.Elevators) do
			for index, floor in pairs(elevatorFloors) do
				CreateThread(function()
					while true do
						local sleep = 2000
						local playerCoords = GetEntityCoords(PlayerPedId())
						local distance = #(playerCoords - floor.coords)
						if distance <= 3.0 then
							sleep = 0
							DrawText3Ds(floor.coords.x,floor.coords.y,floor.coords.z, "Press ~r~E~w~ to use Elevator From " .. floor.level)
							if distance <= 1.5 and IsControlJustReleased(0, 38) then
								local data = {}
								data.elevator = elevatorName
								data.level = index
								TriggerEvent('angelicxs_elevator:showFloors', data)
							end
						end
						Wait(sleep)
					end
				end)
			end
		end
	end
end)
```

you can't create a thread for each position, not to mention calculating the local player's position consecutively to obtain the same result, and the same goes for key detection

**Comment by GouveiaXS** [comment]
That code is only run for people who are using 3D text; requiring a position check every 2 seconds has no impact on client performance regardless of how many elevators are actually utilized (one thread per elevator).

The reason why we separate each elevator into its own thread when using 3Dtext is to prevent cases of 'text flickering' as having all elevators on the same thread does cause issues of stuttering as the code would need to reference each elevator position against the ones found in the config.

Most users put elevators very close together (as MLOs typically have two+ elevators shafts in the same position), in a single thread this can result in the 3Dtext attempting to jump between the two positions unless they reduce the distance even further, which then becomes an issue of being able to see where to press the key to activate the script as it becomes very precise.

**Comment by 766974616c79** [comment]
I understand, I don't agree and I'm not going to try and convince you
