### ISSUE TITLE
problem with context menu. 

### ISSUE THREAD

**Issue by StableBarcodeDev** [GouveiaXS/elevators#4]
Hello i am stucked at a problem.  when i am entering an elevator i have set i get this and i can't teleport to next or lower floor, any help? also is any feature update using ox_lib? 
and thats it my config 

![Screenshot_74](https://user-images.githubusercontent.com/92280829/168444122-cee39f1b-97e2-4238-ae8b-5c7863624e52.png)
![Screenshot_75](https://user-images.githubusercontent.com/92280829/168444158-909b3cc8-ad95-419d-9021-57654ea3f30b.png)

**Comment by GouveiaXS** [comment]
Can you please provide a snip-it of your client side for the event "angelicxs_elevator:showFloors" (approx lines 109-128)

**Comment by WilderMO** [comment]
Hey is there any error message in the logs?

**Comment by StableBarcodeDev** [comment]
No error, i am sending you the event
![Screenshot_93](https://user-images.githubusercontent.com/92280829/169714997-18f1ce0d-1111-4576-b959-09661414efe8.png)

**Comment by WilderMO** [comment]
I think I just saw the problem.

Your Code:
```lua
LaywerMainElevator = {
     {
           ##########################
     },
     {
           ##########################
     },
     {
           ##########################
     },
     {
           ##########################
     },
     {
           ##########################
     },
},
```

Fix :
```lua
LaywerMainElevator = {
     {
           ##########################
     },
     {
           ##########################
     },
     {
           ##########################
     },
     {
           ##########################
     },
     {
           ##########################
     }
},
```

The last floor cant have a comma. Just delete the last comma.
Just try it. It should work.

**Comment by StableBarcodeDev** [comment]
Still the same :(

**Comment by GouveiaXS** [comment]
Are you using the newest version of nh-context?
Does the third eye correctly tell you what elevator spot you are at?
If you change the name of the level argument in the config does that correctly translate?

**Comment by StableBarcodeDev** [comment]
i am not using the latest nh-context because i don't know how to update my other scripts with the new event, 
Yes the third eye correctly tells me where i am.
yes, the only problem is at context it's shows  undendifiend & not teleport

**Comment by GouveiaXS** [comment]
There are changes between how the new nh-context and the old one writes menus. Try using the following at the show floors function; I believe this should follow the old NH-context requirements
table.insert(elevator, {
        header = floor.level,
        txt = floor.label,
        params = {
            event = "angelicxs_elevator:movement",
            arg1 = {
                floor = floor,
            }
        }
    })
    end
    TriggerEvent('nh-context:sendMenu', elevator)

**Comment by StableBarcodeDev** [comment]
now i am getting an error at this line: **RequestCollisionAtCoord(floor.coords.x, floor.coords.y, floor.coords.z)** 
The error says: attempt to index a nil value ( local 'floor' )
