### ISSUE TITLE
couldnt start resource

### ISSUE THREAD

**Issue by Donnyjohn1** [GouveiaXS/elevators#6]
hello i set up the elevator i wanted to use in the config, enabled qb core, set esx to false, but everytime i try to start the live console it will not start the elevator script

**Comment by GouveiaXS** [comment]
What error is it giving?
On Jul 29, 2022 9:50 PM, Donnyjohn1 wrote:


hello i set up the elevator i wanted to use in the config, enabled qb core, set esx to false, but everytime i try to start the live console it will not start the elevator script

-- 
Reply to this email directly or view it on GitHub:
https://github.com/GouveiaXS/elevators/issues/6

**Comment by Jokerkilll** [comment]
I have the same problem 

[ c-resources-core] Could not find dependency qtarget for resource angelicxs_elevators.
[ citizen-server-impl] Couldn't start resource angelicxs_elevators.

qb-target is released, where is problem ?

**Comment by GouveiaXS** [comment]
This script uses qtarget by default for its third eye selection.

If you want to use qb-target there are two things you must do:
1. change qtarget to qb-target in the client side of the script
2. remove qtarget from the dependencies on the fxmanifest

**Comment by VHEEmperor** [comment]
you will have to get nh-context and run it first than the resource will start.
