### ISSUE TITLE
Nothing happens after pushing the button.

### ISSUE THREAD

**Issue by VHEEmperor** [GouveiaXS/elevators#7]
Hello,

I have a issue where no menu appears after using the option with qb-target.

I have edited my xfmanifest depencies
I have changed the line in the client.lua to qb-target instead of qtarget

I have configured my config.lua
https://prnt.sc/ROcnZCqn_fL5
But still after i use qb-target my option on the elevator appears.
But after i click on the option no menu appears nothing. even no error codes.

I am using the latest nh-context

**Comment by GouveiaXS** [comment]
To confirm you get to this step:
![image](https://user-images.githubusercontent.com/99211701/182192283-35746585-dd04-4ea9-be0c-e5c8c08634d7.png)
and once you select Use Elevator you DO NOT get this:
![image](https://user-images.githubusercontent.com/99211701/182192368-416eba0a-650d-440c-9699-bbaf4c6d7dc6.png)

Please confirm that nh-context starts before elevators; also please provide a full copy of the config and client side to confirm.

**Comment by alexvermaning0** [comment]
i will continue this i have the same issue i set it to qb-target instead of qtarget and deleted qtarget dependency
nothing will happen after the first photo. i have nh-context installed and was launched before the elevator script
config: https://pastebin.com/J8P7zVz3
client: https://pastebin.com/SEP20nuN

**Comment by GouveiaXS** [comment]
Are you using nh version nh-context 2.21?
This script will not work with the old nh-context as they have changed the exports names.

**Comment by alexvermaning0** [comment]
> Are you using nh version nh-context 2.21? This script will not work with the old nh-context as they have changed the exports names.

nope i was not . i just searched nh-context and got on https://github.com/nighmares/nh-context page but that is not the right one. now i got the right one from https://github.com/nerohiro/nh-context/releases/tag/v2.21 it works perfectly.
