### ISSUE TITLE
qb-target error

### ISSUE THREAD

**Issue by cummins24v2** [GouveiaXS/elevators#9]
![image](https://user-images.githubusercontent.com/97122395/218275646-99277308-1b1b-419c-9e01-cdbe78de63d1.png)
when i use qb-target i get this error

**Comment by GouveiaXS** [comment]
Based on the screenshot this is strictly a qb-target error. Are there any other indications that this is being caused by the elevator script?

**Comment by H0ssein** [comment]
same problem here

**Comment by GouveiaXS** [comment]
Please provide further detail as the original post does not provide any information I can use to try and fix the issue.

**Comment by H0ssein** [comment]
for me when i activate target it will get nil of this :
`Config.Elevators[data.elevator]` in `angelicxs_elevator:showFloors` event

**Comment by GouveiaXS** [comment]
Can you provide your config so I can see if it is completed correctly?

**Comment by H0ssein** [comment]
its your default config
tested with gabz pillbox

**Comment by H0ssein** [comment]
my problem solved , it was meta_target problem failing add elevator name in options
